language: SQL

services:
    - postgresql

addons:
    postgresql: "9.5"

before_script:
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get install wget ca-certificates
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get upgrade
    - sudo apt-get install postgresql-9.6
    - psql -c 'create database pgmemento_test;' -U postgres
    - psql --version

script:
    - psql -U postgres -d pgmemento_test -a -f INSTALL_PGMEMENTO.sql
